import ReactMarkdown from 'react-markdown'

const policyContent = `# Niel Academy Privacy Policy

**Effective Date:** Monday October 20, 2025  
**Last Updated:** Monday October 20, 2025

---

## 1. Introduction

Welcome to **Niel Academy**.  
Your privacy is important to us. This Privacy Policy explains how we collect, use, store, and protect your personal information when you use the Niel Academy mobile application ("the App").

By using the App, you agree to the terms described in this policy. If you do not agree, please discontinue use of the App.

---

## 2. Who We Are

**Niel Academy**  
Located in **Cameroon**  
Email: **support@nielacademy.com**

Niel Academy provides students with access to learning resources, past exam questions, and intelligent study assistance to enhance understanding and performance.

---

## 3. Information We Collect

We collect only the information necessary to operate the App and provide you with a personalized learning experience.

### 3.1 Information You Provide
- **Google Account Information:** When you sign in, we receive your name, email address, and Google profile ID through Google OAuth.  
- **Payment Information:** When you purchase a subscription, we collect your **phone number** (used for Mobile Money payments) and share it only with our **third-party payment aggregator** for transaction processing.

### 3.2 Information Generated by Your Use of the App
- **Study Progress:** Your scores, attempts, and lesson completion data.  
- **Chat History:** Conversations and interactions within the App to maintain learning continuity.

We **do not collect** unnecessary data such as location, device ID, or contacts.  
We **do not use** analytics, advertising, or tracking tools.

---

## 4. How We Use Your Information

We use your information to:
- Enable login and authentication via Google.  
- Maintain and personalize your learning progress.  
- Process subscription payments securely.  
- Improve your experience within the App.  
- Respond to support requests or inquiries.

We **do not sell or rent** your personal data to anyone.

---

## 5. How We Share Your Information

We only share your information when necessary:
- **Payment Aggregator:** Your phone number is shared securely with our payment partner when you purchase a subscription plan through Mobile Money.  
- **Service Provider (Convex):** We use Convex to securely store your learning and chat data.

We do not share personal data with advertisers, analytics providers, or any unrelated third parties.

---

## 6. Data Storage and Retention

- Your data is securely stored using **Convex** cloud infrastructure.  
- We retain your account data **until you delete your account**.  
- When you delete your account, all associated data (including chats and progress) will be permanently deleted **within 6 months**.

---

## 7. Data Protection and Security

We use reasonable technical and organizational measures to protect your data from unauthorized access, alteration, disclosure, or destruction.  
However, no online system is completely secure; by using the App, you acknowledge that no method of transmission over the internet is 100% risk-free.

---

## 8. Children's Privacy

Niel Academy is designed for students, including those under 18.  
We collect only limited information required for authentication and learning (via Google sign-in and usage data).  
We do not knowingly collect any sensitive information from minors.  
If you believe a child's data has been collected inappropriately, please contact us at **support@nielacademy.com**.

---

## 9. Your Rights

You have the right to:
- Access the personal data we hold about you.  
- Request correction of inaccurate information.  
- Request deletion of your account and associated data.  
- Withdraw consent for data processing (which may limit app functionality).

Requests can be made via **support@nielacademy.com**.

---

## 10. International Transfers

While Niel Academy operates primarily in Cameroon, our service provider (Convex) may store data on servers located outside your country.  
We ensure that any international data transfer is handled securely and in accordance with applicable privacy laws.

---

## 11. Updates to This Policy

We may occasionally update this Privacy Policy to reflect changes in our practices or legal requirements.  
The latest version will always be available at **nielacademy.com/privacy-policy**.  
We encourage you to review it periodically.

---

## 12. Contact Us

If you have any questions or concerns about this Privacy Policy or how we handle your data, please contact us at:  
📧 **support@nielacademy.com**

---`

function PrivacyPolicy() {
  return (
    <div className="flex-1 w-full h-full">
      <section className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="prose prose-lg max-w-none">
          <ReactMarkdown
            components={{
              h1: ({ children }) => (
                <h1 className="text-4xl font-bold text-neutral-900 mb-6 font-roboto-bold">
                  {children}
                </h1>
              ),
              h2: ({ children }) => (
                <h2 className="text-2xl font-semibold text-neutral-900 mb-4 mt-8 font-roboto-semibold">
                  {children}
                </h2>
              ),
              h3: ({ children }) => (
                <h3 className="text-xl font-semibold text-neutral-900 mb-3 mt-6 font-roboto-semibold">
                  {children}
                </h3>
              ),
              p: ({ children }) => (
                <p className="text-neutral-700 text-lg leading-relaxed mb-4 font-serif font-light">
                  {children}
                </p>
              ),
              ul: ({ children }) => (
                <ul className="text-neutral-700 text-lg leading-relaxed mb-4 font-serif font-light list-disc pl-6">
                  {children}
                </ul>
              ),
              li: ({ children }) => (
                <li className="mb-2 font-serif font-light">
                  {children}
                </li>
              ),
              strong: ({ children }) => (
                <strong className="font-semibold text-neutral-900 font-roboto-semibold">
                  {children}
                </strong>
              ),
              hr: () => (
                <hr className="border-neutral-300 my-8" />
              ),
              blockquote: ({ children }) => (
                <blockquote className="border-l-4 border-brand-primary pl-4 italic text-neutral-600 font-serif font-light">
                  {children}
                </blockquote>
              )
            }}
          >
            {policyContent}
          </ReactMarkdown>
        </div>
      </section>
    </div>
  )
}

export default PrivacyPolicy